---
# tasks file for epel

# Install EPEL
- name: install epel
  yum:
    name: epel-release
    state: present
  tags: [ 'packages' ]

- name: enable epel repo
  shell: yum-config-manager --enable epel
  tags: [ 'packages' ]
