---

# Load balancer group from dev hosts file
- hosts: loadbalancer

  # Escalate permissions to use root
  become: yes

  tasks:
    - name: install nginx

    # https://docs.ansible.com/ansible/latest/modules/yum_module.html
      yum:
        name: nginx

        # "present" and "installed" will simply ensure that a desired package is installed.
        # "latest" will update the specified package if it's not of the latest available version.
        state: present

        # Enable a repo for the install/update operation.
        # These repos will not persist beyond the transaction
        enablerepo: epel

        # Force yum to check if cache is out of date and redownload if needed.
        # Has an effect only if state is present or latest.
        update_cache: yes

      
    - name: ensure nginx has started
      service:
        name: nginx
        state: started
        enabled: yes # Whether the service should start on boot