---
# tasks file for python

- name: Install the libselinux-python package
  yum:
    name: libselinux-python
    state: present
  tags: [ 'packages' ]

# Install Python
# https://stackoverflow.com/a/23317640/2442468
- name: install python 3.4
  yum:
    name: [ "gcc", "python34", "python34-setuptools", "python-setuptools-devel", "python34-devel" ]
    state: present
    update_cache: yes
  tags: [ 'packages' ]

# Install Pip
- name: install pip
  easy_install:
    executable: easy_install-3.4
    name: pip
    state: present
  tags: [ 'packages' ]

# Install virtual env
- name: install virtual env
  pip:
    executable: pip3
    name: [ "virtualenv", "virtualenvwrapper"]
    state: present
  tags: [ 'packages' ]
