---

- hosts: loadbalancer
  become: true
  tasks:
    # Returns non-0 exit code if not running
    - name: verify nginx status
      command: service nginx status

    - name: verify nginx is listening on port 80
      wait_for: port=80 timeout=1

    - name: verify nginx is listening on port 8080
      wait_for: port=8080 timeout=1



- hosts: webserver
  become: true
  tasks:
    - name: verify httpd status
      command: service httpd status

    - name: verify httpd is listening on port 80
      wait_for: port=80 timeout=1



- hosts: database
  become: true
  tasks:
    - name: verify mysqld status
      command: service mysqld status

    - name: verify mysqld is listening on port 3306
      wait_for: port=3306 timeout=1