---

- hosts: control
  become: yes
  gather_facts: false

  # Control server is ubuntu

  # https://stackoverflow.com/a/37362559/2442468
  # To access role in a different folder
  roles:
    - { role: roles/control }
