---

- hosts: database
  become: true
  tasks:
    - include_role:
        name: roles/mysql
      vars:
        db_name: demo
        db_user_name: demo
        db_user_password: demo
        db_login_user_name: tyler
        db_login_user_password: tylerlocalhost