---

- hosts: database
  become: true
  tasks:

    # - name: install tools
    #   yum:
    #     name: [ "python2-PyMySQL" ]
    #     state: present
    #     enablerepo: epel
    #     update_cache: yes

    - name: install tools
      yum:
        name: MySQL-python
        state: present
        update_cache: yes

    - name: download mysql server rpm package
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el6-2.noarch.rpm
      become: yes


    - name: confirm rpm package was added
      command: yum repolist all | grep mysql

    
    - name: install mysql server
      yum:
        name: mysql-community-server
        state: present
        update_cache: yes

    - name: ensure mysql started
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: ensure mysql is listening on all ports
      lineinfile:
        dest: /etc/my.cnf
        regexp: ^bind-address
        line: "bind-address = 0.0.0.0"
      notify: restart mysql


    - name: create demo database
      mysql_db:
        name: demo
        state: present
        login_user: root
        login_password: ""

    - name: create demo database user
      mysql_user:
        name: demo
        password: demo
        priv: demo.*:ALL
        host: "%"
        state: present


  handlers:
    - name: restart mysql
      service:
        name: mysqld
        state: restarted