---
# https://github.com/ansible/ansible/issues/9260
- name: get hostvars information
  hosts: all
  remote_user: root
  tasks: []


# Load balancer group from dev hosts file
- hosts: loadbalancer

  # Escalate permissions to use root
  become: yes

  tasks:
    - include_role:
        name: roles/epel
    - include_role:
        name: roles/nginx
      vars:
        sites:
          demo:
            frontend_port: 8080
            backend_port: 80
