---

- hosts: loadbalancer, webserver, database
  become: yes
  
  tasks:
    - name: update yum
      command: yum update -y

    - name: Install the libselinux-python package
      yum:
        name: libselinux-python
        state: present

    # Install EPEL
    - name: install epel
      yum:
        name: epel-release
        state: present

    - name: enable epel repo
      shell: yum-config-manager --enable epel


    # Install Python
    # https://stackoverflow.com/a/23317640/2442468
    - name: install python 3.4
      yum:
        name: [ "gcc", "python34", "python34-setuptools", "python-setuptools-devel", "python34-devel" ]
        state: present
        update_cache: yes

    # Install Pip
    - name: install pip
      easy_install:
        executable: easy_install-3.4
        name: pip
        state: present

    # Install virtual env
    - name: install virtual env
      pip:
        executable: pip3
        name: [ "virtualenv", "virtualenvwrapper"]
        state: present


    - name: install banner
      yum:
        name: figlet
        state: present
        update_cache: yes


- hosts: loadbalancer
  tasks:
    - name: put server name into file
      shell: echo 'Load Balancer' > ~/LoadBalancer.txt

- hosts: webserver
  tasks:
    - name: put server name into file
      shell: echo 'Web Server' > ~/WebServer.txt

- hosts: database
  tasks:
    - name: put server name into file
      shell: echo 'Database' > ~/Database.txt