---

- hosts: loadbalancer, webserver, database
  become: yes
  gather_facts: false

  roles:
    - { role: roles/epel }

  tasks:
    - name: update yum
      command: yum update -y
      tags: [ 'packages' ]

    - name: install banner
      yum:
        name: figlet
        state: present
        update_cache: yes
      tags: [ 'packages' ]

- hosts: loadbalancer
  gather_facts: false
  tasks:
    - name: put server name into file
      shell: echo 'Load Balancer' > ~/LoadBalancer.txt
      args:
        creates: ~/LoadBalancer.txt
      tags: [ 'config' ]


- hosts: webserver
  gather_facts: false
  tasks:
    - name: put server name into file
      shell: echo 'Web Server' > ~/WebServer.txt
      args:
        creates: ~/WebServer.txt
      tags: [ 'config' ]

- hosts: database
  gather_facts: false
  tasks:
    - name: put server name into file
      shell: echo 'Database' > ~/Database.txt
      args:
        creates: ~/Database.txt
      tags: [ 'config' ]
