---

# Bring stack down

- hosts: loadbalancer
  become: yes
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80    state=drained
    - wait_for: port=8080  state=drained

- hosts: webserver
  become: yes
  tasks:
    - service: name=httpd state=stopped
    - wait_for: port=80    state=stopped

# Bring mysql down
# Bring mysql back up

- hosts: database
  become: yes
  tasks:
    - service: name=mysqld state=restarted
    - wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 state=started

# Bring rest of stack back up

- hosts: webserver
  become: yes
  tasks:
    - service: name=httpd state=started
    - wait_for: port=80    state=started

- hosts: loadbalancer
  become: yes
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80    state=started
    - wait_for: port=8080  state=started

