---

- hosts: loadbalancer, webserver, database
  become: yes
  
  tasks:
    - name: update yum
      command: yum update -y

    - name: install banner
      yum:
        name: figlet
        state: present
        update_cache: yes
