---

- hosts: webserver
  become: true
  roles:
    - { role: roles/epel }
    - { role: roles/python }
    - { role: roles/apache }

  tasks:
    - include_role:
        name: roles/demo_app
      vars:
        db_name: demo
        db_user_name: tyler
        db_user_password: tylerlocalhost
