---

- hosts: webserver
  become: true
  tasks:
 
    # in order to install mod_wsgi, you need to install httpd-devel
    - name: install apache
      yum:
        name: [ "httpd", "httpd-devel" ]
        state: present
        update_cache: yes
      notify: restart httpd

    - name: install mysql tools globally
      yum:
        name: [ "mysql-devel", "MySQL-python"]
        state: present
        update_cache: yes

      # need to install mod_wsgi via pip because the one that comes by default with yum is python 2.6
      # which doesn't support dist comprehension (you'll get an invalid syntax from some command within the Flask module)

    - name: install virtualenv
      pip:
        executable: pip3
        name: [ "virtualenv", "mod_wsgi", "mysqlclient" ]
        state: present

    - name: open firewall ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        comment: Apache HTTPD HTTP 80
        state: present
      notify: save iptables
  

    - name: open firewall ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
        comment: Apache HTTPD HTTPS 443
        state: present
      notify: save iptables

    - name: ensure httpd is running
      service:
        name: httpd
        state: started
        enabled: yes


    - name: copy demo app source
      copy:
        src: ../demo/app/ # copy app/ folder with all contents
        dest: /var/www/demo
        mode: 0755
      notify: restart httpd

    # see https://github.com/GrahamDumpleton/mod_wsgi
    # for how I generated this config via `mod_wsgi-express module-config`
    - name: copy apache virtual host config
      copy:
        src: ../demo/demo.conf
        dest: /etc/httpd/conf.d/
        mode: 0755
      notify: restart httpd

    # - name: copy apache wsgi config
    #   copy:
    #     src: ../demo/wsgi.conf
    #     dest: /etc/httpd/conf.d/
    #     mode: 0755
    #   notify: restart httpd

    - name: get mod_wsgi config for apache module
      shell: mod_wsgi-express module-config > /etc/httpd/conf.d/wsgi.conf
      args:
        creates: /etc/httpd/conf.d/wsgi.conf
      notify: restart httpd


    - name: setup python virtual environment
      pip:
        # executable: pip3
        requirements: /var/www/demo/requirements.txt
        virtualenv:   /var/www/demo/venv34
        virtualenv_python: python3.4
      notify: restart httpd


  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

    - name: save iptables
      command: service iptables save
      become: yes
      notify: reload iptables

    - name: reload iptables
      service:
        name: iptables
        state: restarted
